FROM python:3.7-slim-buster
RUN apt-get update
RUN apt-get update && apt-get install -y \
    python3-dev \
    cython3
COPY ./mqtt-handler/requirements.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY mqtt-handler /app
COPY event-orchestrator/* /app/
RUN pip3 install -r /app/requirements.txt
COPY data_classes/* /app/
RUN pip3 install -r /app/requirements.txt
COPY ./common_utils/* /app/
WORKDIR /app
CMD ["/bin/bash"]