import os
from dotenv import load_dotenv, find_dotenv

# load environment variables
load_dotenv(find_dotenv())

TELEMATICS_MQTT_BROKER_HOST = os.getenv("TELEMATICS_MQTT_BROKER_HOST")
TELEMATICS_MQTT_BROKER_HOST_PORT = int(
    os.getenv("TELEMATICS_MQTT_BROKER_HOST_PORT", "8883")
)
TELEMATICS_MQTT_BROKER_AUTH_TOKEN = os.getenv("TELEMATICS_MQTT_BROKER_AUTH_TOKEN")
# LORA MQTT
LORA_MQTT_BROKER_HOST = os.getenv("LORA_MQTT_BROKER_HOST", "mqtt")
LORA_MQTT_BROKER_HOST_PORT = int(os.getenv("LORA_MQTT_BROKER_HOST_PORT", "12183"))
# input
LORA_MQTT_APPLICATION_TOPIC = os.getenv("LORA_MQTT_APPLICATION_TOPIC")
TELEMATICS_MQTT_APPLICATION_TOPIC = os.getenv("TELEMATICS_MQTT_APPLICATION_TOPIC")
# Alerts
TELEMATICS_MQTT_APPLICATION_ALERTS_TOPIC = os.getenv("TELEMATICS_MQTT_ALERTS_TOPIC")
# LORA APPLICATION DETAILS
LORA_APPLICATION_IDENTIFIER = os.getenv("LORA_APPLICATION_IDENTIFIER")
