import os
from dotenv import load_dotenv, find_dotenv

# load environment variables
load_dotenv(find_dotenv())

TELEMATICS_MQTT_BROKER_HOST = os.getenv("TELEMATICS_MQTT_BROKER_HOST", "mqtt")
TELEMATICS_MQTT_BROKER_HOST_PORT = int(
    os.getenv("TELEMATICS_MQTT_BROKER_HOST_PORT", "12183")
)
TELEMATICS_MQTT_BROKER_AUTH_TOKEN = os.getenv("TELEMATICS_MQTT_BROKER_AUTH_TOKEN")
TELEMATICS_MQTT_BROKER_SSL_ENABLED = eval(
    os.getenv("TELEMATICS_MQTT_BROKER_SSL_ENABLED", True)
)
# LORA MQTT
LORA_MQTT_BROKER_HOST = os.getenv("LORA_MQTT_BROKER_HOST")
LORA_MQTT_BROKER_HOST_PORT = int(os.getenv("LORA_MQTT_BROKER_HOST_PORT", "8883"))
LORA_MQTT_BROKER_AUTH_TOKEN = os.getenv("LORA_MQTT_BROKER_AUTH_TOKEN")
# input
LORA_MQTT_APPLICATION_TOPIC = os.getenv("LORA_MQTT_APPLICATION_TOPIC")
# Alerts
TELEMATICS_MQTT_APPLICATION_ALERTS_TOPIC = os.getenv(
    "TELEMATICS_MQTT_APPLICATION_ALERTS_TOPIC"
)
TELEMATICS_MQTT_PUBLISHER_ALERTS = os.getenv("TELEMATICS_MQTT_PUBLISHER_ALERTS")
# LORA APPLICATION DETAILS
LORA_APPLICATION_IDENTIFIER = os.getenv("LORA_APPLICATION_IDENTIFIER")
